doc: document config-manager plugin
rpm-software-management/dnf5 pull request #1356
Opened 2024-03-28 20:06 UTC by jrohel

2024-04-02 18:23 UTC, evan-goode requested changes
Overall I think this is clear and well-structured. There's a lot of detail about the behavior of each subcommand and how the different overrides files interact, but I think it's warranted. The structure of our configuration is complex, and users will undoubtedly run into some edge case with config-manager and turn to this doc page to find out what's going on.

Something big that's missing is documentation of the changes from the DNF 4 config-manager plugin. The CLI is completely different: https://dnf-plugins-core.readthedocs.io/en/latest/config_manager.html, I'm sure for good reason, but when reading this page, the first goal of many users will be to figure out how to update their DNF 4 scripts.

This could be done in a separate PR, but I would like to see a section added to https://dnf5.readthedocs.io/en/latest/changes.html about config-manager that has examples of DNF 4 commands and their (rough?) DNF 5 equivalents.

2024-04-02 18:23 UTC, evan-goode commented on doc/dnf5_plugins/config-manager.8.rst
> +      The variables "releasever_major" and "releasever_minor" are read-only. Their values are generated from the "releasever" variable.
Good thought to include this bit about read-only variables.

2024-04-02 18:23 UTC, evan-goode commented on doc/dnf5_plugins/config-manager.8.rst
> +    | Download "additional.repo", test it and put it in repository configuration directory.
Add comma: `test it, and put it`

2024-04-02 18:23 UTC, evan-goode commented on doc/dnf5_plugins/config-manager.8.rst
> +``dnf5 config-manager setopt *-debuginfo.gpgcheck=0``
Maybe put single quotes around these wildcards, or else the shell would expand them.

2024-04-10 05:16 UTC, jrohel commented on doc/dnf5.8.rst
> +    | :manpage:`dnf5-config-manager(8)`, :ref:`Config-manager command <config_manager_plugin_ref-label>`
OK. I'll leave it as it is. We should unify the documentation in another PR.

2024-04-10 07:07 UTC, jrohel commented
@evan-goode Thank you for your review.

2024-04-10 21:32 UTC, evan-goode approved these changes
Great, thanks!

2024-04-10 21:33 UTC, merged