Add history rollback command and transaction merging
rpm-software-management/dnf5 pull request #1558
Opened 2024-06-24 11:46 UTC by kontura

Merging is used to revert multiple transactions to achieve a rollback.

2024-06-24 12:24 UTC, kontura commented
Tests update: https://github.com/rpm-software-management/ci-dnf-stack/pull/1515

2024-06-27 21:22 UTC, evan-goode commented
Basic functionality looks good! I'll do a code review tomorrow.

2024-07-01 21:22 UTC, evan-goode requested changes
I tested this some more and it works well. It's great to have so many test cases in `test_transaction_merge.cpp`.

2024-07-02 12:37 UTC, kontura commented on libdnf5/transaction/transaction_merge.cpp
> +                    // Actions cancel out
Sounds good, I will throw an exception in the new `else` block since it hard to foresee what could the new item action do.

2024-07-02 12:53 UTC, kontura commented on libdnf5/transaction/transaction_merge.cpp
> +            // When the previous action is REASON_CHANGE or REINSTALL override it (act as if its not there),
Possibly, I meant the comment as an explanation for the `if` condition.
I tried moving the comment to `else` branch now and to me it felt more confusing.

Though you are right, it is talking about when the `else` branch is taken.

2024-07-02 14:10 UTC, evan-goode approved these changes

2024-07-02 14:11 UTC, evan-goode commented
Thanks! Since the CI is failing due to librepo 1.18 not being available, I will run the tests locally and merge when they finish.

2024-07-02 20:36 UTC, evan-goode commented
Tests passing!

2024-07-02 20:36 UTC, merged