expired-pgp-keys: New plugin for detecting expired PGP keys
rpm-software-management/dnf5 pull request #1592
Opened 2024-07-24 12:34 UTC by jan-kolarik

Based on the implementation from https://github.com/rpm-software-management/dnf-plugins-core/pull/533.

Workaround for: https://github.com/rpm-software-management/dnf5/issues/1192.

2024-07-25 10:06 UTC, jrohel commented
I looked into the source code. It's a rewrite of the new "expired-gpg-keys" plugin from DNF4 to libdnf5.

And here's the problem. The original plugin is in Python. It is not part of the libdnf library -> this makes it ignored by users using libdnf directly - `microdnf`, `PackageKit`, ... And it behaves more like an application plugin - it interacts with the user via the console.

This PR implements the `libdnf5` plugin. So it is a library plugin. The advantage is that it will be active for all users of the `libdnf5` library (`dnf5` application, `dnf5daemon-server`, ...). However, the library must not interfere with the console. For example, `dnf5daemon-server` does not have a console to communicate with the user - it is a background daemon. 

The `dnf5` application only supports "command" plugins. And generally making this plugin as an application plugin is not a good way to go. The same problem would occur as with DNF4. It would not work for other applications (users of the libdnf5 library).

How to get out of this?
We need an interface defined in the `libdnf5` library for this case. 
Queries whether to do key import are done via callbacks. Similarly, queries to remove them (with possible information why) should be handled via callbacks.

2024-07-25 10:16 UTC, jan-kolarik commented
> I looked into the source code. It's a rewrite of the new "expired-gpg-keys" plugin from DNF4 to libdnf5.
> 
> And here's the problem. The original plugin is in Python. It is not part of the libdnf library -> this makes it ignored by users using libdnf directly - `microdnf`, `PackageKit`, ... And it behaves more like an application plugin - it interacts with the user via the console.
> 
> This PR implements the `libdnf5` plugin. So it is a library plugin. The advantage is that it will be active for all users of the `libdnf5` library (`dnf5` application, `dnf5daemon-server`, ...). However, the library must not interfere with the console. For example, `dnf5daemon-server` does not have a console to communicate with the user - it is a background daemon.
> 
> The `dnf5` application only supports "command" plugins. And generally making this plugin as an application plugin is not a good way to go. The same problem would occur as with DNF4. It would not work for other applications (users of the libdnf5 library).
> 
> How to get out of this? We need an interface defined in the `libdnf5` library for this case. Queries whether to do key import are done via callbacks. Similarly, queries to remove them (with possible information why) should be handled via callbacks.

That's a good point Jarek, I wasn't thinking about non-CLI users here. I will rework the plugin as you've suggested, thanks for that!

2024-08-14 07:33 UTC, pmatilai commented
Looking at the expiriation date will miss what I think is the more common issue just now: all the obsolete SHA1 based signatures that will fail in various other ways. Sequoia generally defers this checking to verify rather than import time, but you might want to additionally call pgpPubKeyLint() on the key material to catch at least some of those issues too.

2025-01-28 09:26 UTC, jan-kolarik commented
I performed some manual testing, and everything appears to be working as expected. One potential minor issue is that when GPG keys are available remotely (e.g., Copr keys), users always see output about downloading the keys, like this:
```
[kolage@ecstatic_dewdney dnf5]# dnf upgrade libdnf
Updating and loading repositories:
Repositories loaded.
 https://download.copr.fedorainfracloud. 100% |  13.9 KiB/s |   1.0 KiB |  00m00s
 https://download.copr.fedorainfracloud. 100% |  12.2 KiB/s |   1.0 KiB |  00m00s
...
```
This happens because the `FileDownloader` in the `RpmSignature` class uses the standard download callbacks from the `Base` class, and there’s currently no proper way to customize these callbacks for one-time use.

2025-01-28 09:27 UTC, jan-kolarik commented
This PR adds a new libdnf5 workflow hook at the `Resolved` stage, enabling custom logic to be added immediately after the goal is resolved. Related updates were also made to the `Actions` plugin to support this new behavior.

2025-01-29 09:46 UTC, jan-kolarik commented
**How to test:**

If the plugin is enabled and any COPR repository is enabled on your system, you can test it by faketiming the system date and disabling `sslverify`, then running a transaction. This should trigger a prompt to remove the PGP key:

```
faketime '+5years' dnf5 install nudoku --setopt=sslverify=False
```

CI tests will be delivered in a follow-up PR.

2025-01-29 14:34 UTC, jan-kolarik commented
The only failing CI test seems to be about updating the Actions CI test text expectation.

2025-01-30 11:55 UTC, jrohel requested changes
Thank you. Nice work. I wrote comments what still needs to be resolved.

2025-01-30 11:55 UTC, jrohel commented on libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp
> +    rpmdbFreeIterator(mi);
I'm not sure if this is mandatory, but at least in general it's a good idea to release the iterators first and then the transaction.

2025-01-30 11:55 UTC, jrohel commented on dnf5/context.cpp
> +                         _("The following PGP key (0x{}) has expired on {}:"),
The `repokey_remove` callback is called before the key is removed and allows you to confirm or deny its removal.

The message "The following PGP key (0x{}) expired on {}:" may be wrong. We do not know who called the callback and why they want to remove the key. It could was the expired-pgp-keys plugin. But also some other plugin, which for example will check if the key has been revoked. Or whether the key is still on the company's list of allowed keys. The reason for removing the key could be different.

2025-02-05 13:56 UTC, jrohel commented on include/libdnf5/plugin/iplugin.hpp
> +};
Please add destructor with `= default` definition in cpp file.

2025-02-05 21:21 UTC, jrohel approved these changes

2025-02-05 21:23 UTC, jrohel commented
Thank you.

2025-02-05 21:47 UTC, merged