doc: TransactionCallbacks class documentation
rpm-software-management/dnf5 pull request #1670
Opened 2024-09-03 06:10 UTC by m-blaha

Add missing documentation to rpm transaction callbacks.

Resolves: https://github.com/rpm-software-management/dnf5/issues/1658

2024-09-05 08:10 UTC, m-blaha commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// @param nevra Nevra of the package that triggered scriptlet execution
Thank you, I tried to clarify it.

2024-09-06 08:26 UTC, jrohel commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// @param item The TransactionPackage class instance for the package that owns the executed or triggered scriptlet. It can be `nullptr` if th  e scriptlet owner is not part of the transaction.
`th e` -> `the`

2024-09-06 08:26 UTC, jrohel commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// @param item The TransactionPackage class instance for the package that owns the executed or triggered scriptlet. It can be `nullptr` if th  e scriptlet owner is not part of the transaction.
`th e` -> `the`

2024-09-06 08:28 UTC, jrohel commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// cpio error during the package installation. Currentl not used by librpm.
`Currentl` -> `Currently`

2024-09-06 08:40 UTC, m-blaha commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// @param item The TransactionPackage class instance for the package that owns the executed or triggered scriptlet. It can be `nullptr` if th  e scriptlet owner is not part of the transaction.
Agh! Sorry for these typos, fixed.

2024-09-06 08:41 UTC, m-blaha commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// @param item The TransactionPackage class instance for the package that owns the executed or triggered scriptlet. It can be `nullptr` if th  e scriptlet owner is not part of the transaction.
Fixed.

2024-09-06 08:41 UTC, m-blaha commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// cpio error during the package installation. Currentl not used by librpm.
Fixed.

2024-09-06 09:55 UTC, jrohel requested changes
Thank you for the PR.
I added one more minor change request in the review.  The change is important in order to properly generate documentation for the Python API.

2024-09-06 09:55 UTC, jrohel commented on include/libdnf5/rpm/transaction_callbacks.hpp
> +    /// @param amount The portion of the package already installed
Please add empty doc line after description. Do this for all methods.
Replace:
```
/// Report the package installation progress periodically.
/// @param item The TransactionPackage class instance for the package currently being installed
/// @param amount The portion of the package already installed

```
with:
```
/// Report the package installation progress periodically.
///
/// @param item The TransactionPackage class instance for the package currently being installed
/// @param amount The portion of the package already installed
```

The blank line is important for proper generation of documentation for Python.

2024-09-06 11:20 UTC, jrohel approved these changes

2024-09-06 11:21 UTC, merged