Reimplement `--color` flag
rpm-software-management/dnf5 pull request #1750
Opened 2024-10-02 15:43 UTC by alimirjamali

resolves: https://github.com/rpm-software-management/dnf5/issues/839
related: https://github.com/QubesOS/qubes-issues/issues/9482

2024-10-02 17:50 UTC, alimirjamali commented
The `fedora-39-*` unit-tests failure were discussed here:
https://github.com/rpm-software-management/dnf5/pull/1735#issuecomment-2385138020

I am not sure about other test failures with.

2025-03-13 16:08 UTC, alimirjamali commented
@jrohel Hi. I did not see that you have self-assigned yourself to the issue. Please let me know if I should rebase the PR and continue working on it, or possibly you are working on a better solution.

2025-03-18 11:50 UTC, jrohel requested changes
Hi. Thanks for the PR. You can keep working. I did a review.

2025-03-18 11:50 UTC, jrohel commented on doc/dnf5.8.rst
> +    | Control whether color is used in terminal output. Valid values are ``always``, ``never`` and ``auto`` (default).
Valid values are:
- `always`, `on`, `yes`, `1`, `true`
- `never`, `off`, `no`, `0`, `false`
- `auto`, `tty`, `if-tty`

So we are fully compatible with DNF4. It also accepts all the values listed. But the truth is that the DNF4 man page only lists `always`, `never`, and `auto`. I am considering whether we want to ignore the other possible values in the documentation again.

It may be practical to know about the possibility to write `--color=1` instead of `--color=always` and `--color=0` instead of `--color=never`.

2025-03-18 11:50 UTC, jrohel commented on libdnf5-cli/tty.cpp
> +bool colorized = true;  // Review notes: Maybe encapsulate this in a class
The `colorized` variable is a private variable. It is not in the header file and is only accessed within that file. Please make it `static`.

2025-03-18 11:50 UTC, jrohel commented on include/libdnf5-cli/tty.hpp
> +LIBDNF_CLI_API bool is_colorized();
I'm thinking of names. Actually the function does not return whether the tty is colored. It returns the user's preference of whether or not they want colors based on what they set with `set_colorized`. So on a colored `tty` it may return `false` and vice versa.

But I can't think of a better name... `set_use_colors`, `get_use_colors` ... I don't know

2025-03-19 00:13 UTC, alimirjamali commented on dnf5/main.cpp
> +    color->set_const_value("auto");
Done

2025-03-19 00:13 UTC, alimirjamali commented on dnf5/main.cpp
> +        auto & colorized = base.get_config().get_color_option().get_value();
Done

2025-03-19 00:16 UTC, alimirjamali commented on doc/dnf5.8.rst
> +    | Control whether color is used in terminal output. Valid values are ``always``, ``never`` and ``auto`` (default).
> So we are fully compatible with DNF4. It also accepts all the values listed. But the truth is that the DNF4 man page only lists `always`, `never`, and `auto`. I am considering whether we want to ignore the other possible values in the documentation again.

Yes. That was exactly what I did (copy/pasting from DNF4 man page). Please let me know how this should read and I will amend the PR accordingly

2025-03-19 00:16 UTC, alimirjamali commented on libdnf5-cli/tty.cpp
> +bool colorized = true;  // Review notes: Maybe encapsulate this in a class
done

2025-03-19 00:20 UTC, alimirjamali commented
> Hi. Thanks for the PR. You can keep working. I did a review.

Hi. Thanks for the review. I rebased the PR (to resolve a merge conflict and for testing purpose) and applied the advised changes. Awaiting CI/CD checks and further instructions for the remaining issues.

2025-03-19 11:43 UTC, jrohel commented on include/libdnf5-cli/tty.hpp
> +LIBDNF_CLI_API bool is_colorized();
And if we keep the convention with `is` we get:
`void coloring_enable(bool)` and `bool is_coloring_enabled()`

2025-03-19 11:52 UTC, jrohel commented on doc/dnf5.8.rst
> +    | Control whether color is used in terminal output. Valid values are ``always``, ``never`` and ``auto`` (default).
Frankly, I can't think of an appropriate description. Therefore, leave the documentation as you have written it.

2025-03-20 07:44 UTC, jrohel commented
Thank you for the changes. I realized we had a problem. PR changes the default coloring behavior from `auto` to `always`. This breaks other applications using libdnf5-cli that don't call `coloring_enable`. For example, dnf5daemon. 

I am looking for a simple solution. For example:
- Add to "include/libdnf5-cli/tty.hpp":
 `enum class ColoringEnabled { AUTO, ALWAYS, NEVER };`

- Change "libdnf5-cli/tty.cpp" to:
```
static ColoringEnabled coloring = ColoringEnabled::AUTO;

void coloring_enable(ColoringEnabled value) {
    coloring = value;
}

bool is_coloring_enabled() {
    return coloring == ColoringEnabled::AUTO ? is_interactive() : coloring == ColoringEnabled::ALWAYS;
}
```
- Change "dnf5-main.cpp" to:
```
            auto & coloring = base.get_config().get_color_option().get_value();
            if (coloring == "always") {
                libdnf5::cli::tty::coloring_enable(libdnf5::cli::tty::ColoringEnabled::ALWAYS);
            } else if (coloring == "never") {
                libdnf5::cli::tty::coloring_enable(libdnf5::cli::tty::ColoringEnabled::NEVER);
            } else if (libdnf5::cli::tty::is_interactive()) {
                libdnf5::cli::tty::coloring_enable(libdnf5::cli::tty::ColoringEnabled::ALWAYS);
            } else {
                libdnf5::cli::tty::coloring_enable(libdnf5::cli::tty::ColoringEnabled::NEVER);
            }
```

2025-03-20 13:58 UTC, alimirjamali commented
> I am looking for a simple solution. For example:

The suggested solution (with some minor changes) passed most of the CI/CD tests. Local tests also pass (two failed before applying the suggestions). Thanks for guidance.

BTW, I rebased before applying the suggestions. For the remaining pending issues:

1. Clang [error](https://github.com/rpm-software-management/dnf5/actions/runs/13969632312/job/39107947794?pr=1750#step:9:271) is unrated to this specific PR. But I can fix the bug in this PR if necessary.
2. To the best of my understanding, the failed test scenario (`dnf/plugins-core/expired-pgp-keys.feature`) should be solved after by either of PR 2145 or 2147 (hopefully).

2025-03-20 17:16 UTC, jrohel commented
Thank you for the PR. The failed tests are not due to this PR. I'm merging it.

2025-03-20 17:37 UTC, jrohel approved these changes

2025-03-20 17:37 UTC, merged