Python API: `add_new_download` return `None` regression test
rpm-software-management/dnf5 pull request #1933
Opened 2024-12-05 18:13 UTC by evan-goode

`DownloadCallbacks.add_new_download` can now return either `None` or an `int`. This adds a regression test to check that `add_new_download` can still return `None`.

2024-12-12 08:10 UTC, jrohel requested changes
Thank you for the unit test.

Please remove the unnecessary `test_instance` class variable.

2024-12-13 16:32 UTC, evan-goode commented
Done and rebased.

2024-12-16 09:21 UTC, jrohel approved these changes

2024-12-16 09:21 UTC, jrohel commented
Thanks

2024-12-16 09:22 UTC, merged