spec: Fix conditional for dnf-data
rpm-software-management/dnf5 pull request #691
Opened 2023-06-30 18:01 UTC by sgallagher

The spec for DNF 5 doesn't build properly on ELN/RHEL10. These conditionals get it building correctly, but there are test failures and I haven't figured out what's causing them yet.

2023-07-05 17:18 UTC, yselkowitz requested changes

2023-07-05 17:18 UTC, yselkowitz commented on dnf5.spec
> +%if (0%{?fedora} && 0%{?fedora} < 39) || (0%{?rhel} && 0%{?rhel} < 10)
```suggestion
%if ! (0%{?fedora} > 38 || 0%{?rhel} > 9)
```

2023-07-05 17:18 UTC, yselkowitz commented on dnf5.spec
> +%if 0%{?fedora} <= 38 || 0%{?rhel} > 9
```suggestion
%if ! (0%{?fedora} > 38 || 0%{?rhel} > 9)
```

2023-07-20 17:04 UTC, sgallagher commented
Sorry for the delay. This should be better now.

2023-07-21 09:40 UTC, j-mracek commented
LGTM

2023-07-21 09:40 UTC, merged