state: Store and load system repo groups metadata
rpm-software-management/dnf5 pull request #86
Opened 2022-10-11 14:54 UTC by m-blaha

Comps metadata for each installed group is now stored in the system state and loaded into libsolv pool from there.

2022-10-13 11:17 UTC, jrohel commented on libdnf/repo/solv_repo.cpp
> +                    logger.debug(
Is this really a "debug" message? Is it logging something that is standard behavior?  It looks more like a warning. We want to warn the user that a loading error has occurred.

2022-10-26 11:20 UTC, jan-kolarik commented on libdnf/system/state.cpp
> +std::vector<std::string> State::installed_groups() {
I would prefer ``get_installed_groups`` here.

2022-10-26 13:24 UTC, jan-kolarik requested changes
I left some comments above, they are addressing some minor issues from my point of view. Also a rebase is needed now. Otherwise LGTM.

2022-10-27 07:55 UTC, m-blaha commented on libdnf/base/transaction.cpp
> +                group.dump(comps_xml_dir / (group.get_groupid() + ".xml"));
I remember that python json and xml libraries use `dump()` method name for printing the content of element to string / file. But I like your suggestion and I've added a commit for renaming the methods.

2022-10-27 07:55 UTC, m-blaha commented on libdnf/system/state.cpp
> +std::vector<std::string> State::installed_groups() {
Renamed.

2022-10-27 08:49 UTC, merged